- name: Install automysqlbackup
  apt: name={{ item }} state=present
  with_items:
  - automysqlbackup

- name: Configure automysqlbackup
  template: src=automysqlbackup.template dest=/etc/default/automysqlbackup
